import Mathlib.Algebra.Category.Grp.Adjunctions
import Mathlib.Algebra.Category.Grp.ForgetCorepresentable
import Mathlib.CategoryTheory.Adjunction.Whiskering
import Mathlib.CategoryTheory.Preadditive.Projective.Basic
import Mathlib.CategoryTheory.Sites.ConcreteSheafification
import Mathlib.CategoryTheory.Sites.ConstantSheaf
import Mathlib.Topology.Sheaves.Abelian

/-!
# Free abelian sheaves on open sets

The free abelian sheaf on the representable presheaf of an open set represents
sections on that open. Consequently it is projective whenever epimorphisms of
abelian sheaves are surjective on those sections.
-/

noncomputable section

namespace Aoki

open CategoryTheory TopologicalSpace Opposite

universe u

variable {X : TopCat.{u}}

/-- The free abelian sheaf generated by the representable presheaf of `W`. -/
def freeOpen (W : Opens X) : TopCat.Sheaf AddCommGrpCat.{u} X :=
  (presheafToSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
    (yoneda.obj W ⋙ AddCommGrpCat.free)

/-- Maps from `freeOpen W` to `M` are precisely sections of `M` on `W`. -/
def freeOpenHomEquiv (W : Opens X) (M : TopCat.Sheaf AddCommGrpCat.{u} X) :
    (freeOpen W ⟶ M) ≃ M.obj.obj (op W) :=
  ((sheafificationAdjunction (Opens.grothendieckTopology X) AddCommGrpCat.{u}).homEquiv
    (yoneda.obj W ⋙ AddCommGrpCat.free) M).trans
      (((AddCommGrpCat.adj.whiskerRight (Opens X)ᵒᵖ).homEquiv
        (yoneda.obj W) M.obj).trans yonedaEquiv)

/-- The map of free sheaves induced by inclusion of open sets. -/
def freeOpenMap {V W : Opens X} (i : V ⟶ W) : freeOpen V ⟶ freeOpen W :=
  (presheafToSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).map
    (Functor.whiskerRight (yoneda.map i) AddCommGrpCat.free)

/-- The free sheaf construction, functorially in the open set. -/
def freeOpenFunctor (X : TopCat.{u}) : Opens X ⥤ TopCat.Sheaf AddCommGrpCat.{u} X :=
  yoneda ⋙ (Functor.whiskeringRight _ _ _).obj AddCommGrpCat.free ⋙
    presheafToSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}

@[simp] theorem freeOpenFunctor_obj (W : Opens X) :
    (freeOpenFunctor X).obj W = freeOpen W := rfl

@[simp] theorem freeOpenFunctor_map {V W : Opens X} (i : V ⟶ W) :
    (freeOpenFunctor X).map i = freeOpenMap i := rfl

/-- The representing equivalence is additive. -/
def freeOpenHomAddEquiv (W : Opens X) (M : TopCat.Sheaf AddCommGrpCat.{u} X) :
    (freeOpen W ⟶ M) ≃+ M.obj.obj (op W) where
  toEquiv := freeOpenHomEquiv W M
  map_add' _ _ := rfl

/-- The representing equivalence is natural in the coefficient sheaf. -/
theorem freeOpenHomEquiv_naturality (W : Opens X)
    {M N : TopCat.Sheaf AddCommGrpCat.{u} X} (f : freeOpen W ⟶ M) (g : M ⟶ N) :
    freeOpenHomEquiv W N (f ≫ g) =
      g.hom.app (op W) (freeOpenHomEquiv W M f) := by
  rfl

set_option backward.isDefEq.respectTransparency false in
/-- Precomposing with an inclusion of free opens corresponds to restricting
the represented section. -/
theorem freeOpenHomEquiv_restrict {V W : Opens X} (i : V ⟶ W)
    (M : TopCat.Sheaf AddCommGrpCat.{u} X) (f : freeOpen W ⟶ M) :
    freeOpenHomEquiv V M (freeOpenMap i ≫ f) =
      M.obj.map i.op (freeOpenHomEquiv W M f) := by
  change CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u} at M
  simp only [freeOpenHomEquiv, Equiv.trans_apply, freeOpenMap]
  erw [(sheafificationAdjunction (Opens.grothendieckTopology X) AddCommGrpCat.{u}).homEquiv_naturality_left
    (Functor.whiskerRight (yoneda.map i) AddCommGrpCat.free) f]
  erw [(AddCommGrpCat.adj.whiskerRight (Opens X)ᵒᵖ).homEquiv_naturality_left (yoneda.map i)]
  exact (yonedaEquiv_naturality _ i).symm

/-- Surjectivity of every epimorphism on `W`-sections makes the free sheaf on
`W` projective. No topological condition on `W` is assumed here. -/
theorem projective_freeOpen_of_surjective (W : Opens X)
    (hW : ∀ (M N : TopCat.Sheaf AddCommGrpCat.{u} X) (p : M ⟶ N) [Epi p],
      Function.Surjective (p.hom.app (op W))) : Projective (freeOpen W) := by
  constructor
  intro M N f p hp
  obtain ⟨s, hs⟩ := hW M N p (freeOpenHomEquiv W N f)
  refine ⟨(freeOpenHomEquiv W M).symm s, ?_⟩
  apply (freeOpenHomEquiv W N).injective
  rw [freeOpenHomEquiv_naturality, Equiv.apply_symm_apply, hs]

/-- The free sheaf on the entire space is the constant integral sheaf used
as the first argument in the definition of ordinary sheaf cohomology. -/
def freeOpenTopIso (X : TopCat.{u}) :
    freeOpen (⊤ : Opens X) ≅
      (constantSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
        (AddCommGrpCat.of (ULift.{u} ℤ)) := by
  let ev : TopCat.Sheaf AddCommGrpCat.{u} X ⥤ Type u :=
    (sheafSections (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
      (op (⊤ : Opens X)) ⋙ forget AddCommGrpCat.{u}
  let hfree : ev.CorepresentableBy (freeOpen (⊤ : Opens X)) :=
    { homEquiv := freeOpenHomEquiv ⊤ _
      homEquiv_comp := fun g f => freeOpenHomEquiv_naturality ⊤ f g }
  let hconst : ev.CorepresentableBy
      ((constantSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
        (AddCommGrpCat.of (ULift.{u} ℤ))) :=
    { homEquiv := fun {M} =>
        ((constantSheafAdj (Opens.grothendieckTopology X) AddCommGrpCat.{u}
          (Limits.isTerminalTop (α := Opens X))).homEquiv _ M).trans
          (AddCommGrpCat.uliftZMultiplesAddEquiv (M.obj.obj (op ⊤))).toEquiv
      homEquiv_comp := fun _ _ => rfl }
  exact hfree.uniqueUpToIso hconst

end Aoki
