import Aoki.Sheaf.ProjectiveOpen
import Mathlib.Algebra.Category.ModuleCat.Adjunctions
import Mathlib.Algebra.Category.ModuleCat.AB
import Mathlib.Algebra.Category.ModuleCat.FilteredColimits

/-!
# Free module sheaves on open sets

The sheafification of the free module on an open representable represents
sections. Compact opens, and arbitrary disjoint unions of compact opens,
therefore represent projective objects in the category of module sheaves.
-/

noncomputable section

namespace Aoki

open CategoryTheory TopologicalSpace Opposite
open TopCat.Presheaf

universe u

variable (R : Type u) [CommRing R] {X : TopCat.{u}}

/-- The free `R`-module sheaf generated by the representable of `W`. -/
def freeOpenModule (W : Opens X) : TopCat.Sheaf (ModuleCat.{u} R) X :=
  (presheafToSheaf (Opens.grothendieckTopology X) (ModuleCat.{u} R)).obj
    (yoneda.obj W ⋙ ModuleCat.free R)

/-- Maps from the free module sheaf are sections on its representing open. -/
def freeOpenModuleHomEquiv (W : Opens X) (M : TopCat.Sheaf (ModuleCat.{u} R) X) :
    (freeOpenModule R W ⟶ M) ≃ M.obj.obj (op W) :=
  ((sheafificationAdjunction (Opens.grothendieckTopology X) (ModuleCat.{u} R)).homEquiv
    (yoneda.obj W ⋙ ModuleCat.free R) M).trans
      ((((ModuleCat.adj R).whiskerRight (Opens X)ᵒᵖ).homEquiv
        (yoneda.obj W) M.obj).trans yonedaEquiv)

/-- The morphism induced by an inclusion of opens. -/
def freeOpenModuleMap {V W : Opens X} (i : V ⟶ W) :
    freeOpenModule R V ⟶ freeOpenModule R W :=
  (presheafToSheaf (Opens.grothendieckTopology X) (ModuleCat.{u} R)).map
    (Functor.whiskerRight (yoneda.map i) (ModuleCat.free R))

/-- The free module sheaf, functorially in the open. -/
def freeOpenModuleFunctor (X : TopCat.{u}) :
    Opens X ⥤ TopCat.Sheaf (ModuleCat.{u} R) X :=
  yoneda ⋙ (Functor.whiskeringRight _ _ _).obj (ModuleCat.free R) ⋙
    presheafToSheaf (Opens.grothendieckTopology X) (ModuleCat.{u} R)

@[simp] theorem freeOpenModuleFunctor_obj (W : Opens X) :
    (freeOpenModuleFunctor R X).obj W = freeOpenModule R W := rfl

@[simp] theorem freeOpenModuleFunctor_map {V W : Opens X} (i : V ⟶ W) :
    (freeOpenModuleFunctor R X).map i = freeOpenModuleMap R i := rfl

/-- The representing equivalence is additive. -/
def freeOpenModuleHomAddEquiv (W : Opens X)
    (M : TopCat.Sheaf (ModuleCat.{u} R) X) :
    (freeOpenModule R W ⟶ M) ≃+ M.obj.obj (op W) where
  toEquiv := freeOpenModuleHomEquiv R W M
  map_add' _ _ := rfl

/-- Naturality in the target sheaf. -/
theorem freeOpenModuleHomEquiv_naturality (W : Opens X)
    {M N : TopCat.Sheaf (ModuleCat.{u} R) X}
    (f : freeOpenModule R W ⟶ M) (g : M ⟶ N) :
    freeOpenModuleHomEquiv R W N (f ≫ g) =
      g.hom.app (op W) (freeOpenModuleHomEquiv R W M f) := by
  rfl

set_option backward.isDefEq.respectTransparency false in
/-- Inclusions of the representing opens act by restriction of sections. -/
theorem freeOpenModuleHomEquiv_restrict {V W : Opens X} (i : V ⟶ W)
    (M : TopCat.Sheaf (ModuleCat.{u} R) X) (f : freeOpenModule R W ⟶ M) :
    freeOpenModuleHomEquiv R V M (freeOpenModuleMap R i ≫ f) =
      M.obj.map i.op (freeOpenModuleHomEquiv R W M f) := by
  change CategoryTheory.Sheaf (Opens.grothendieckTopology X) (ModuleCat.{u} R) at M
  simp only [freeOpenModuleHomEquiv, Equiv.trans_apply, freeOpenModuleMap]
  erw [(sheafificationAdjunction (Opens.grothendieckTopology X) (ModuleCat.{u} R)).homEquiv_naturality_left
    (Functor.whiskerRight (yoneda.map i) (ModuleCat.free R)) f]
  erw [((ModuleCat.adj R).whiskerRight (Opens X)ᵒᵖ).homEquiv_naturality_left (yoneda.map i)]
  exact (yonedaEquiv_naturality _ i).symm

/-- Surjectivity of epimorphisms on these sections implies projectivity. -/
theorem projective_freeOpenModule_of_surjective (W : Opens X)
    (hW : ∀ (M N : TopCat.Sheaf (ModuleCat.{u} R) X) (p : M ⟶ N) [Epi p],
      Function.Surjective (p.hom.app (op W))) : Projective (freeOpenModule R W) := by
  constructor
  intro M N f p hp
  obtain ⟨s, hs⟩ := hW M N p (freeOpenModuleHomEquiv R W N f)
  refine ⟨(freeOpenModuleHomEquiv R W M).symm s, ?_⟩
  apply (freeOpenModuleHomEquiv R W N).injective
  rw [freeOpenModuleHomEquiv_naturality, Equiv.apply_symm_apply, hs]

/-- The free sheaf on the whole space is the constant sheaf of the rank-one
module `R`, the tensor unit of module sheaves. -/
def freeOpenModuleTopIso (X : TopCat.{u}) :
    freeOpenModule R (⊤ : Opens X) ≅
      (constantSheaf (Opens.grothendieckTopology X) (ModuleCat.{u} R)).obj
        (ModuleCat.of R R) := by
  let ev : TopCat.Sheaf (ModuleCat.{u} R) X ⥤ Type u :=
    (sheafSections (Opens.grothendieckTopology X) (ModuleCat.{u} R)).obj
      (op (⊤ : Opens X)) ⋙ forget (ModuleCat.{u} R)
  let hfree : ev.CorepresentableBy (freeOpenModule R (⊤ : Opens X)) :=
    { homEquiv := freeOpenModuleHomEquiv R ⊤ _
      homEquiv_comp := fun g f => freeOpenModuleHomEquiv_naturality R ⊤ f g }
  let hconst : ev.CorepresentableBy
      ((constantSheaf (Opens.grothendieckTopology X) (ModuleCat.{u} R)).obj
        (ModuleCat.of R R)) :=
    { homEquiv := fun {M} =>
        ((constantSheafAdj (Opens.grothendieckTopology X) (ModuleCat.{u} R)
          (Limits.isTerminalTop (α := Opens X))).homEquiv _ M).trans
          (ModuleCat.homEquiv.trans
            (LinearMap.ringLmapEquivSelf R R (M.obj.obj (op ⊤))).toEquiv)
      homEquiv_comp := fun _ _ => rfl }
  exact hfree.uniqueUpToIso hconst

/-- Module-valued sections on disjoint opens are automatically compatible. -/
theorem module_compatible_of_pairwise_disjoint
    (M : TopCat.Sheaf (ModuleCat.{u} R) X) {ι : Type u} (W : ι → Opens X)
    (hW : Pairwise (fun a b => Disjoint (W a) (W b)))
    (s : ∀ i, M.obj.obj (op (W i))) : IsCompatible M.obj W s := by
  intro i j
  by_cases hij : i = j
  · subst j
    rfl
  · apply TopCat.Presheaf.IsSheaf.section_ext M.property
    intro x hx
    have hempty : W i ⊓ W j = ⊥ := disjoint_iff.mp (hW hij)
    simp only [hempty, Opens.mem_bot] at hx

/-- Local lifts of an epimorphism glue after passing to a disjoint refinement. -/
theorem surjective_module_sections_of_disjoint_refinements
    (W : Opens X) (hW : HasDisjointOpenRefinements W)
    (M N : TopCat.Sheaf (ModuleCat.{u} R) X) (p : M ⟶ N) [Epi p] :
    Function.Surjective (p.hom.app (op W)) := by
  classical
  intro s
  have hlocal := (TopCat.Presheaf.isLocallySurjective_iff p.hom).mp
    ((TopCat.Sheaf.isLocallySurjective_iff_epi p).mpr inferInstance)
  have hl : ∀ x : W, ∃ V : Opens X, ∃ hVW : V ≤ W,
      ∃ t : M.obj.obj (op V), p.hom.app (op V) t = N.obj.map (homOfLE hVW).op s ∧
        (x : X) ∈ V := by
    intro x
    obtain ⟨V, hVW, ⟨t, ht⟩, hx⟩ := hlocal W s x x.property
    exact ⟨V, hVW, t, ht, hx⟩
  choose V hVW t ht hx using hl
  have hcover : W ≤ iSup V := by
    intro x hxW
    exact (le_iSup V ⟨x, hxW⟩) (hx ⟨x, hxW⟩)
  obtain ⟨κ, Z, j, hdisj, hZV, hcoverZ⟩ := hW W V hVW hcover
  have hZW : ∀ a, Z a ≤ W := fun a => (hZV a).trans (hVW (j a))
  let sf : ∀ a, M.obj.obj (op (Z a)) :=
    fun a => M.obj.map (homOfLE (hZV a)).op (t (j a))
  obtain ⟨t', ht', _⟩ := M.existsUnique_gluing' Z W
    (fun a => homOfLE (hZW a)) hcoverZ sf
    (module_compatible_of_pairwise_disjoint R M Z hdisj sf)
  refine ⟨t', ?_⟩
  apply N.eq_of_locally_eq' Z W (fun a => homOfLE (hZW a)) hcoverZ
  intro a
  erw [← NatTrans.naturality_apply, ht']
  dsimp only [sf]
  erw [NatTrans.naturality_apply, ht]
  erw [← ConcreteCategory.comp_apply, ← Functor.map_comp]
  rfl

variable [T2Space X] [TotallyDisconnectedSpace X]

/-- Module-sheaf epimorphisms are surjective on compact-open sections. -/
theorem surjective_module_sections_of_isCompact
    (W : Opens X) (hW : IsCompact (W : Set X))
    (M N : TopCat.Sheaf (ModuleCat.{u} R) X) (p : M ⟶ N) [Epi p] :
    Function.Surjective (p.hom.app (op W)) :=
  surjective_module_sections_of_disjoint_refinements R W
    (hasDisjointOpenRefinements_of_isCompact W hW) M N p

/-- The free module sheaf represented by a compact open is projective. -/
theorem projective_freeOpenModule_of_isCompact
    (W : Opens X) (hW : IsCompact (W : Set X)) : Projective (freeOpenModule R W) :=
  projective_freeOpenModule_of_surjective R W
    (surjective_module_sections_of_isCompact R W hW)

/-- Arbitrary small disjoint unions of compact opens also represent projectives. -/
theorem projective_freeOpenModule_disjoint_iSup {ι : Type u} (W : ι → Opens X)
    (hcompact : ∀ i, IsCompact (W i : Set X))
    (hdisj : Pairwise (fun i j => Disjoint (W i) (W j))) :
    Projective (freeOpenModule R (iSup W)) := by
  apply projective_freeOpenModule_of_surjective
  exact surjective_module_sections_of_disjoint_refinements R _
    (HasDisjointOpenRefinements.disjoint_iSup W hdisj
      (fun i => hasDisjointOpenRefinements_of_isCompact (W i) (hcompact i)))

end Aoki
